### ISSUE TITLE
Rendering SLS 'base:zabbix.proxy' failed: Jinja variable 'dict object' has no attribute 'includes'

### ISSUE THREAD

**Issue by asenci** [saltstack-formulas/zabbix-formula#109]
Incorrect dictionary key access is causing a rendering issue for zabbix/agent/init.sls and zabbix/proxy/init.sls:

2019-03-05 09:59:45,059 [salt.state       :3462][CRITICAL][52888] Rendering SLS 'base:zabbix.proxy' failed: Jinja variable 'dict object' has no attribute 'includes'
2019-03-05 10:04:09,998 [salt.utils.templates:181 ][ERROR   ][54057] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 170, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 403, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'includes'

The code:
```      {% for include in settings.get('includes', defaults.includes) %} ```
Should be changed to:
```       {% for include in settings.get('includes', defaults['includes']) %} ```

**Comment by xenadmin** [comment]
That is so strange. I introduced this change through #105 not long ago. I'm still very new at salt, but as I find it relative easy to read, I copied the working concept over from the zabbix agent files if I remember correctly. I have used that change at several opportunities by now, and didn't have any difficulties. No rendering errors whatsoever. I'm a 100% Debian 9 Stretch with 2018.3.3.

**Comment by asenci** [comment]
Yeah, I found it a bit strange as well. The zabbix.agent sls was also affected.
Possibly the test cases didn't involve using the default value (i.e. 'include' not defined on the pillar)?
